# Generated by Django 5.0 on 2024-02-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0004_delete_mainmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumedfood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calapp.calmodel')),
            ],
        ),
    ]
