# Generated by Django 5.0 on 2024-02-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0005_dropdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdo',
            name='quantity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
