# Generated by Django 5.0 on 2024-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0007_finalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calmodel',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calmodel',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
